/* Object Class:
    It is the superclass of all classes in Java. It is present inside java.lang package.
    It provides some methods which are common to all the objects.
    Some commonly used methods of Object class are:
        1. toString(): It returns the string representation of the object.
        2. equals(Object obj): It compares the current object with the specified object.
        3. hashCode(): It returns the hash code value of the object.
        4. getClass(): It returns the runtime class of the object.
        5. clone(): It creates and returns a copy of the object.
        6. finalize(): It is called by the garbage collector before destroying the object.
        7. wait(), wait(long l), wait(long l, int i), notify(), notifyAll(): These methods are used for inter-thread communication.

        toString() Method:
            The return type of toString() method is String.
            It is used to return address of the object in the form of string.

        Why do we need to override toString() method?
            By default, the toString() method returns a string that consists of the class name, the at-sign character '@', and the unsigned hexadecimal representation of the hash code of the object.
            This default representation is not very informative.
            Therefore, we override the toString() method to provide a meaningful string representation of the object.
            To print data of an object rather than its address.

        hashCode() Method:
            The hashCode() method returns an integer value, generated by a hashing algorithm.
            It is used in hashing based collections like HashMap, HashSet, etc.
            The hash code of an object is used to determine the bucket location in the hash table where the object will be stored.

        equals() Method:
            The return type of equals() method is boolean.
            The equals() method is used to compare two objects for equality.
            By default, the equals() method compares the memory addresses of the objects (i.e., it checks if both references point to the same object).

            Why do we need to override equals() method?
                If we want to compare the actual data of the objects rather than their memory addresses, we need to override the equals() method in our class.
*/
public class Objects {
    String name;
    int id;

    Objects(String name, int id) {
        this.name = name;
        this.id = id;
    }

    // @Override
    // public String toString() {
    //     return "Objects{name='" + name + "', id=" + id + "}";
    // }

    @Override
    public boolean equals(Object obj) {

        Objects ref = (Objects) obj;
        return this.id == ref.id && this.name == (ref.name);
    }
    public static void main(String[] args) {
        // Objects obj = new Objects("Aditya", 101);
        // System.out.println(obj.toString());

        // Objects ref = new Objects("Aditya", 101);
        // System.out.println("HashCode of ref: " + ref.hashCode());
        // Objects ref2 = new Objects("Aditya", 101);
        // System.out.println("HashCode of ref2: " + ref2.hashCode());
        // System.out.println(Integer.toHexString(ref.hashCode())); // 372f7a8d
        // System.out.println(ref); // 372f7a8d
        
        // System.out.println((ref.getClass())); // class Objects
        // System.out.println(ref.getClass().getName()); // Objects
        
        // System.out.println(ref.getClass().getName() + "@" + Integer.toHexString(ref.hashCode())); // Objects@372f7a8d

        Objects ref1 = new Objects("Aditya", 101);
        Objects ref2 = new Objects("Aditya", 101);

        System.out.println(ref1.equals(ref2)); // false before overriding equals() method, true after overriding equals() method
        System.out.println(ref1 == ref2); // false
    }
}
